name: Create PR
on: 
  push:
    branches:
        - 'resume'
    paths:
        - 'public/resume.pdf'
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout code
            uses: actions/checkout@v3
        - name: Upload
          run: |
            # configure git
            git config --global user.name "Utsav Deep"
            git config --global user.email "utsavdeep01@gmail.com"
        -   name: Create Pull Request
            run: gh pr create -B main -H resume --title '[GITHUB ACTION] Updated Resume' --body 'This PR was created automatically by Github Actions for updated resume file to be merged to main branch' --label gh-resume
            env:
                GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"