name: merge PR
on: 
  pull_request:
    types:
        - opened
    branches:
        - 'main'
    paths:
        - 'public/resume.pdf'
jobs:
    merge_pr:
        timeout-minutes: 10
        if: contains(github.event.pull_request.labels.*.name, 'gh-resume')
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Output PR number
                run: |
                    echo "${{ github.event.number }}"
            -   name: Wait for build to succeed
                uses: fountainhead/action-wait-for-check@v1.1.0
                id: wait-for-build
                with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: test
                  intervalSeconds: 30
                  ref: ${{ github.event.pull_request.head.sha || github.sha }}
            -   name: Merge PR
                run: gh pr merge $PR_NUMBER --merge
                env:
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                    PR_NUMBER: "${{ github.event.number }}"
            -   name: Delete remote branch
                run: |
                    git push origin --delete resume